### ISSUE TITLE
Add -O to browserify build

### ISSUE THREAD

**Issue by wiz** [slamdata/purescript-halogen-template#1]
Without it even this tiny app kicks in at 800Kb. Not good for public performances ;)

**Comment by garyb** [comment]
I did think it was absurdly large, but [according to this](https://github.com/bodil/pulp#making-a-javascript-bundle) `--to` implies `--optimize`. Apparently that isn't true though, as it's much smaller now. 7af4c7091ccaaf0f2fc41f906e2a25ffdf468ac9

Thanks!

**Comment by wiz** [comment]
Hmm.. The relevant secion is https://github.com/bodil/pulp#optimising-code-size

The pulp's `build` does imply -O, but `browserify` doesn't as the speed apparently suffers due to losing the browserify incremental builds. Decisions... decisions...

**Comment by garyb** [comment]
It seems pretty snappy for this sample project at least, I think it's a sensible default to have. For development you'd perhaps want to use `pulp server` or something anyway, but I figured explaining pulp's was out of scope for this quickstart kind of thing.
