### ISSUE TITLE
xmlns:foo?

### ISSUE THREAD

**Issue by JamieBallingall** [slamdata/purescript-halogen-template#18]
https://github.com/slamdata/purescript-halogen-template/blob/cebbb9fd48d438b5223c07630cc6104ec0e5d4cd/dist/index.html#L2

creates a namespace called 'foo'. Is that required? Given it the connotations of 'foo' as a placeholder name it creates confusion around the role of SVG in Halogen apps.

I believe it could simply be removed, since SVG would be within the HTML document and therefore unable to have its own namespace anyway.

**Comment by garyb** [comment]
Uh yes, absolutely, I have no idea why that is in there!
