### ISSUE TITLE
Can't build cloned repo

### ISSUE THREAD

**Issue by mrkgnao** [slamdata/purescript-halogen-template#5]
I did the following about five minutes or so ago.

* `sudo npm install purescript pulp bower -g`
* `git clone <...> halogen-test`
* `npm run build`

I get an `invalid option --censor-lib` error.

Output of `npm run build`:
```
mrkgnao@underflow ~/c/p/halogen-test> npm run build

> purescript-halogen@ build /home/mrkgnao/code/ps/halogen-test
> pulp build --censor-lib --strict

* Building project in /home/mrkgnao/code/ps/halogen-test
Invalid option `--censor-lib'

Usage: psc [FILE] [-o|--output ARG] [--no-tco] [--no-magic-do] [--no-opts]
           [-v|--verbose-errors] [-c|--comments] [--source-maps]
           [-p|--no-prefix] [--json-errors]
* ERROR: Subcommand terminated with exit code 1

npm ERR! Linux 4.6.2-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.6
npm ERR! code ELIFECYCLE
npm ERR! purescript-halogen@ build: `pulp build --censor-lib --strict`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the purescript-halogen@ build script 'pulp build --censor-lib --strict'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the purescript-halogen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pulp build --censor-lib --strict
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs purescript-halogen
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls purescript-halogen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mrkgnao/code/ps/halogen-test/npm-debug.log
```

Here is the output of `pulp build`:
```
mrkgnao@underflow ~/c/p/halogen-test> pulp build
* Building project in /home/mrkgnao/code/ps/halogen-test
psc: No files found using pattern: bower_components/purescript-*/src/**/*.purs
Error found:
at /home/mrkgnao/code/ps/halogen-test/src/Halogen/Component.purs line 464, column 28 - line 464, column 28

  Unable to parse module:
  unexpected =
  expecting :, , or }


See https://github.com/purescript/purescript/wiki/Error-Code-ErrorParsingModule for more information,
or to contribute content related to this error.


* ERROR: Subcommand terminated with exit code 1
mrkgnao@underflow ~/c/p/halogen-test> npm run build

> purescript-halogen@ build /home/mrkgnao/code/ps/halogen-test
> pulp build --censor-lib --strict

* Building project in /home/mrkgnao/code/ps/halogen-test
Invalid option `--censor-lib'

Usage: psc [FILE] [-o|--output ARG] [--no-tco] [--no-magic-do] [--no-opts]
           [-v|--verbose-errors] [-c|--comments] [--source-maps]
           [-p|--no-prefix] [--json-errors]
* ERROR: Subcommand terminated with exit code 1
```

~~If it helps, I'm on a fresh (yesterday) Arch install, and I'm having some problems with Unicode for some reason that make `yaourt` say things like `nÂ°` instead of "nº" or whatever it is supposed to say.~~ Fixed, doesn't help.

**Comment by garyb** [comment]
Are you sure this is the repo you're cloning? Those `--strict --censor-lib` flags are for use with `purescript-psa`, and neither of which are used in the build script currently: https://github.com/slamdata/purescript-halogen-template/blob/960f2f1128b7ceea0c29ed4326fff2f3479c9a71/package.json

If you `npm install -g purescript-psa` it will fix the errors with the flags (or just `npm install`, as all the dependencies are listed and will be installed locally instead), but I'm pretty sure it's the main Halogen repo you've cloned rather than this.

**Comment by mrkgnao** [comment]
I may have made that mistake, so I nuked my local copy and re-cloned it. Following the steps gave me a huge bunch of compiler errors about `qualified`s where they shouldn't have been.

Doing `npm install` without the `--production` works fine; I think the real problem is the breaking changes from PureScript v0.9.1. Maybe you could update the README to reflect this?

**Comment by garyb** [comment]
There's a PR to Halogen that is pretty far along that will fix it up for PS 0.9, so at this point we may as well get wait and get that sorted out - hopefully I'll be able to make a release later today and then update this repo accordingly.

**Comment by mrkgnao** [comment]
That's nice to hear.

**Comment by garyb** [comment]
Sorry it didn't happen quite as speedily as I said, but this repo is now updated for the latest Halogen, which in turn has been updated to work with PureScript 0.9.1 and the 1.0 core libraries.
