### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by vyorkin** [slamdata/purescript-halogen-template#9]
steps to reproduce:

1) clone repo
2) `bower i`
3) `npm run build`

[![asciicast](https://asciinema.org/a/2qdoy9rhj9te8fi1v5zk06oll.png)](https://asciinema.org/a/2qdoy9rhj9te8fi1v5zk06oll)

**Comment by garyb** [comment]
1. Did you `npm i` / `npm i --production` too?
2. Does `dist` exist in the cloned repo?

**Comment by vyorkin** [comment]
1. no, I thought its not required (going to try it now)
2. nope(

**Comment by vyorkin** [comment]
@garyb Just did `npm i` and `bower i` before `npm run build` – the same error (`Error: ENOENT: no such file or directory, open 'dist/app.js'`)

**Comment by garyb** [comment]
That's odd, `dist` should definitely be present! (See here in the GitHub view: https://github.com/slamdata/purescript-halogen-template/tree/master/dist)

Perhaps try re-cloning?

**Comment by vyorkin** [comment]
yeah, going to try everything from scratch now

**Comment by vyorkin** [comment]
yes, everything is fine now
